### PR TITLE
Restructed docs a bit and wrote a bunch more

### PR DESCRIPTION
**Pull request by evert**
This can definitely use some proof-reading. It's quite hard to figure out how much to explain.

### CODE REVIEW

**Comment by evert** [comment]
@ikbensiep , now I've written a couple of these, i feel that maybe the documentation layout can use a bit more love:

image

Bit hard to exactly explain, but page feels a bit crowded, especially around the code sample. Maybe the left-margin should be a lot higher?

**Comment by ikbensiep** [comment]
> page feels a bit crowded

Yeah the first thing I noticed when I pulled this was the lack of whitespace. Must've gone in between the cracks somewhere. :shrug:  Added back some of that intended whitespace around headings and code blocks.

I also added a couple of  utils to allow for a _bit_  richer authoring options, see the 'testdocs' page (added to docs menu for convenience for now, screenshot below): 

Screenshot from 2022-09-20 16-43-09

**Comment by evert** [comment]
<3 the note styles!

**Review by ikbensiep — APPROVED** [review]
awesome :writing_hand:

**Pull request merged**
