### PR TITLE
Modernize for docs

### PR DESCRIPTION
**Pull request by mhum**
This still needs a bunch of love.

### Homepage: Main CTAs
Something needs to be done with thes. `Learn More` still links to the section below, but the `Install` doesn't. Maybe this should be a link to the docs instead?
image

### Homepage: More Information
Something needs to be done with this `More Information` section on the bottom of the home page. These can probably be links in the top nav instead.
image

### Documentation: Landing page
This doesn't exist yet! Needs to be made. Should probably exist at `/doc` or something.

### Documentation: Getting Started Landing
`/getting-started` exists, but it's _all_ of the Getting Started content. This probably needs a landing page and then sub-pages for the different things. Should probably live under docs? Something like `/docs/getting-started`.

### Documentation: Left Nav
Looks ugly and needs some love. The `Middleware` links isn't collapsible, but it should be. None of the links currently highlight when you're on that page. It's also not responsive at all.
image

### Middleware: Landing
The overall page could use some love as well as the boxes themselves. I'm thinking that `More info` should be pushed to the bottom on the left and a link to the Github repo on the bottom right. Also, the right in-page nav shows and probably shouldn't on this page.
image

### Middleware: Pages
There's something wrong with the page styling when you go to a specific page. I haven't gotten to these yet, so not sure what the problem is. Compare the below screenshot to the above. The left nav isn't sticky, the right in-page nav is squashed in the middle, and the page title doesn't appear in the correct place.
image

### General Layout: Footer
The footer is massive. Should be a long smaller. Also maybe sticky to the bottom like the navbar is to the top?

### General Layout: Top Nav
Needs some more links! Also, could be cool to have the Curveball logo on the top right and maybe the next, too. Maybe on every page except for the homepage? Whatever looks best.

### General Layout: Shared layouts
I've been hacking away at the documentation page, so there isn't currently an overall shared layout that can be used by different layouts/pages. Might be worth creating an overall layout (for the homepage), one with a left nav (for the docs), and maybe one with no left nav for random things (this could just be the one for the homepage).

### Jekyll Infra
I updated Jekyll from v3 to v4 and installed some Gems. Based on our internal conversations, I guess we can't do that? This repo is set up pretty differently from the BG website, so unsure what should be done specifically to get this working.

### CODE REVIEW

**Review by evert — APPROVED** [review]
Awesome!

**Comment by evert** [comment]
> I updated Jekyll from v3 to v4 and installed some Gems. Based on our internal conversations, I guess we can't do that? This repo is set up pretty differently from the BG website, so unsure what should be done specifically to get this working.

Correct, we can't use any gems. We're basically stuck to whatever github pages provides, which is this:

https://pages.github.com/versions/

Having a GemFile is still useful for local dev though, although github pages recommends using their 'github-pages' gem which itself depends on all the gems they use.

https://github.com/github/pages-gem

**Comment by evert** [comment]
Will it be possible to manually sort the items in the navigation? Correctly they are sorted alphabetically and I think it would be better to have some control here.

**Comment by mhum** [comment]
> Will it be possible to manually sort the items in the navigation? Correctly they are sorted alphabetically and I think it would be better to have some control here.

Yeah. I've seen people use a `weight` field in the front matter to do the sorting. FYI @ikbensiep

**Comment by ikbensiep** [comment]
> > Will it be possible to manually sort the items in the navigation? Correctly they are sorted alphabetically and I think it would be better to have some control here.
> 
> Yeah. I've seen people use a `weight` field in the front matter to do the sorting. FYI @ikbensiep

In `_config.yml` I'm manually sorting this way (in getting started only):

```yaml
collections_dir: collections
collections:
  getting-started:
    output: true
    order: 
    - basics.md
    - aws-lamdba.md
    - azure.md
    - bun.md
    - node.md
  middleware:
    output: true
  api:
    output: true
```

**Pull request closed without merging**
